dist: xenial
sudo: false
language: node_js
node_js:
- '10'
python:
  - "3.5"
cache:
  - pip
  - npm
branches:
  only:
  - master
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_613e8e5d4c40_key -iv $encrypted_613e8e5d4c40_iv -in ./travis/external-services.js.enc -out ./src/assets/external-services.js -d
install:
- npm install
- pip install awscli
script:
- npm run build -- --aot=true --prod=true
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: autonomy-pwa.test.bitmark.com
  skip_cleanup: true
  local_dir: "./dist/autonomy"
  region: ap-northeast-1
  on:
    branch: dev
after_deploy:
- aws configure set preview.cloudfront true
- test $TRAVIS_BRANCH = "dev" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_STAGING_DISTRIBUTION_ID --paths "/*"
