dist: xenial
sudo: required
language: node
node_js:
- '10'
env:
  global:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GO111MODULE=on
cache:
  npm: true
  directories:
  - $GOPATH/pkg/mod
branches:
  only:
  - master
  - dev
before_install:
- eval "$(gimme stable)"
install:
- go version
- cd src/bitmarksdk && npm install && npm run build
script:
- cd ../.. && npm install
- if [ "$TRAVIS_BRANCH" = "dev" ]; then npm run build -- --configuration staging; fi
- if [ "$TRAVIS_BRANCH" = "master" ]; then npm run build -- --configuration production; fi
- cd ./dist/autonomy
- mv index.html manifest.webmanifest ../../lambda/handlers/html-template/
- find .  -type f -exec gzip {} \; -exec mv {}.gz {} \;
- cd ../../
before_deploy:
- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
- unzip -qq awscliv2.zip
- sudo ./aws/install
- if [ "$TRAVIS_BRANCH" = "dev" ]; then aws s3 rm s3://$S3_BUCKET/ --recursive ; fi
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  local_dir: "./dist/autonomy"
  region: ap-northeast-1
  edge: true
  default_text_charset: utf-8
  max_threads: 10
  detect_encoding: true
  cache_control: "max-age=31536000: *.jpg, *.svg, *.gif, *.png, *.webp, *.css, *.js, *.ico, *wasm"
  on:
    all_branches: true

after_deploy:
- cd lambda/handlers/html-template && AWS_DEFAULT_REGION=us-east-1 ./deploy.sh && cd ../../../
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
