dist: xenial
sudo: required
language: go
node_js:
- '10'
go:
- 1.14.x
env:
  global:
    - GO111MODULE=on
cache:
  npm: true
  directories:
  - $GOPATH/pkg/mod
branches:
  only:
  - master
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_613e8e5d4c40_key -iv $encrypted_613e8e5d4c40_iv -in ./travis/js/external-services.js.enc -out ./src/assets/js/external-services.js -d
install:
- cd src/bitmarksdk && npm install && npm run build
script:
- cd ../.. && npm install && npm run build -- --aot=true --prod=true
before_deploy:
- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
- unzip -qq awscliv2.zip
- sudo ./aws/install
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: autonomy-pwa.test.bitmark.com
  local_dir: "./dist/autonomy"
  region: ap-northeast-1
  edge: true
  detect_encoding: true
  default_text_charset: utf-8
  max_threads: 10
  cache_control: "max-age=31536000: *.jpg, *.svg, *.gif, *.png, *.webp, *.css, *.js, *.ico"
  on:
    branch: dev
after_deploy:
- aws configure set preview.cloudfront true
- test $TRAVIS_BRANCH = "dev" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_STAGING_DISTRIBUTION_ID --paths "/*"
